version: '3.8'

services:
  service-a:
    build:
      context: ./services/service_a
    container_name: service-a
    command: python app.py
    ports:
      - "5001:5000"
    networks:
      - monitoring_net
    restart: always

  service-b:
    build:
      context: ./services/service_b
    container_name: service-b
    command: python app.py
    ports:
      - "5002:5000"
    networks:
      - monitoring_net
    restart: always

  service-c:
    build:
      context: ./services/service_c
    container_name: service-c
    command: python app.py
    ports:
      - "5003:5000"
    networks:
      - monitoring_net
    restart: always

  service-d:
    build:
      context: ./services/service_d
    container_name: service-d
    command: python app.py
    ports:
      - "5004:5000"
    networks:
      - monitoring_net
    restart: always



networks:
  monitoring_net:
    driver: bridge