name: Fault Injection Data Collection

on:
  workflow_dispatch:
    inputs:
      num_experiments_per_job:
        description: 'Number of experiments per fault type per job'
        required: true
        default: '25'
      services:
        description: 'Services to inject faults into (space-separated)'
        required: true
        default: 'service_a service_b service_c service_d'

jobs:
  fault-injection:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    strategy:
      fail-fast: false
      matrix:
        job_index: [0, 1, 2, 3]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build all services (force no-cache)
      run: |
        docker-compose build --no-cache

    - name: Start services
      run: |
        docker-compose up -d
        sleep 30

    - name: Show container status
      run: |
        docker-compose ps
        docker-compose logs service-a || true
        docker-compose logs service-b || true
        docker-compose logs service-c || true
        docker-compose logs service-d || true

    - name: Wait for all services to be healthy
      run: |
        for port in 5001 5002 5003 5004; do
          echo "Waiting for service on port $port to be ready..."
          until curl -sf http://localhost:$port/metrics; do sleep 2; done
          echo "Service on port $port is ready."
        done
        echo "All services are healthy."

    - name: Start monitoring
      run: |
        python scripts/run_monitoring.py &
        sleep 10

    - name: Run fault injection batch
      run: |
        START_ID=$(( ${{ matrix.job_index }} * ${{ github.event.inputs.num_experiments_per_job }} ))
        END_ID=$(( (${{ matrix.job_index }} + 1) * ${{ github.event.inputs.num_experiments_per_job }} ))
        echo "Running experiments from $START_ID to $END_ID"
        python scripts/run_experiments.py --start-id $START_ID --end-id $END_ID

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: fault-injection-results-${{ matrix.job_index }}
        path: |
          results/
        retention-days: 30

    - name: Clean up
      if: always()
      run: |
        docker-compose down
        docker system prune -f
